### ISSUE TITLE
EisensteinHu - with or without BAOs?

### ISSUE THREAD

**Issue by cbehren** [federicomarulli/CosmoBolognaLib#5]
It is no clear to me whether the implemented EisensteinHu transfer function includes the BAO wiggles or not. From the reference in the class documentation, it seems that this is the no wiggle TF. It would be great if this could be clarified.

**Comment by federicomarulli** [comment]
Yes, this is the no wiggle TF.

**Comment by cbehren** [comment]
Thanks for the quick reply! Is there an interest in integrating the one with wiggles?

**Comment by federicomarulli** [comment]
Yes, I think it'd be worth to integrate it, for BAO analyses it might be useful (as it should be much faster than the other codes now included)

**Comment by cbehren** [comment]
I guess I am going to implement it anyways, so I can just provide what I have, then.

**Comment by federicomarulli** [comment]
Great!

**Comment by cbehren** [comment]
I sent you an email with the code.
